import {
    GiCardAceSpades, GiCard2Spades, GiCard3Spades, GiCard4Spades, GiCard5Spades, GiCard6Spades, GiCard7Spades, GiCard8Spades, GiCard9Spades, GiCard10Spades, GiCardJackSpades, GiCardQueenSpades, GiCardKingSpades,
    GiCardAceClubs, GiCard2Clubs, GiCard3Clubs, GiCard4Clubs, GiCard5Clubs, GiCard6Clubs, GiCard7Clubs, GiCard8Clubs, GiCard9Clubs, GiCard10Clubs, GiCardJackClubs, GiCardQueenClubs, GiCardKingClubs, GiCardJoker,
    GiCardAceHearts, GiCard2Hearts, GiCard3Hearts, GiCard4Hearts, GiCard5Hearts, GiCard6Hearts, GiCard7Hearts, GiCard8Hearts, GiCard9Hearts, GiCard10Hearts, GiCardJackHearts, GiCardQueenHearts, GiCardKingHearts,
    GiCardAceDiamonds, GiCard2Diamonds, GiCard3Diamonds, GiCard4Diamonds, GiCard5Diamonds, GiCard6Diamonds, GiCard7Diamonds, GiCard8Diamonds, GiCard9Diamonds, GiCard10Diamonds, GiCardJackDiamonds, GiCardQueenDiamonds, GiCardKingDiamonds,
} from "react-icons/gi";

export const deck = [
    {"value": 1, "number": "A", "suit": "♠", "color": "black", "icon": GiCardAceSpades},
    {"value": 2, "number": "2", "suit": "♠", "color": "black", "icon": GiCard2Spades},
    {"value": 3, "number": "3", "suit": "♠", "color": "black", "icon": GiCard3Spades},
    {"value": 4, "number": "4", "suit": "♠", "color": "black", "icon": GiCard4Spades},
    {"value": 5, "number": "5", "suit": "♠", "color": "black", "icon": GiCard5Spades},
    {"value": 6, "number": "6", "suit": "♠", "color": "black", "icon": GiCard6Spades},
    {"value": 7, "number": "7", "suit": "♠", "color": "black", "icon": GiCard7Spades},
    {"value": 8, "number": "8", "suit": "♠", "color": "black", "icon": GiCard8Spades},
    {"value": 9, "number": "9", "suit": "♠", "color": "black", "icon": GiCard9Spades},
    {"value": 10, "number": "10", "suit": "♠", "color": "black", "icon": GiCard10Spades},
    {"value": 11, "number": "J", "suit": "♠", "color": "black", "icon": GiCardJackSpades},
    {"value": 12, "number": "Q", "suit": "♠", "color": "black", "icon": GiCardQueenSpades},
    {"value": 13, "number": "K", "suit": "♠", "color": "black", "icon": GiCardKingSpades},
    {"value": 1, "number": "A", "suit": "♣", "color": "black", "icon": GiCardAceClubs},
    {"value": 2, "number": "2", "suit": "♣", "color": "black", "icon": GiCard2Clubs},
    {"value": 3, "number": "3", "suit": "♣", "color": "black", "icon": GiCard3Clubs},
    {"value": 4, "number": "4", "suit": "♣", "color": "black", "icon": GiCard4Clubs},
    {"value": 5, "number": "5", "suit": "♣", "color": "black", "icon": GiCard5Clubs},
    {"value": 6, "number": "6", "suit": "♣", "color": "black", "icon": GiCard6Clubs},
    {"value": 7, "number": "7", "suit": "♣", "color": "black", "icon": GiCard7Clubs},
    {"value": 8, "number": "8", "suit": "♣", "color": "black", "icon": GiCard8Clubs},
    {"value": 9, "number": "9", "suit": "♣", "color": "black", "icon": GiCard9Clubs},
    {"value": 10, "number": "10", "suit": "♣", "color": "black", "icon": GiCard10Clubs},
    {"value": 11, "number": "J", "suit": "♣", "color": "black", "icon": GiCardJackClubs},
    {"value": 12, "number": "Q", "suit": "♣", "color": "black", "icon": GiCardQueenClubs},
    {"value": 13, "number": "K", "suit": "♣", "color": "black", "icon": GiCardKingClubs},
    {"value": 1, "number": "A", "suit": "♥", "color": "red", "icon": GiCardAceHearts},
    {"value": 2, "number": "2", "suit": "♥", "color": "red", "icon": GiCard2Hearts},
    {"value": 3, "number": "3", "suit": "♥", "color": "red", "icon": GiCard3Hearts},
    {"value": 4, "number": "4", "suit": "♥", "color": "red", "icon": GiCard4Hearts},
    {"value": 5, "number": "5", "suit": "♥", "color": "red", "icon": GiCard5Hearts},
    {"value": 6, "number": "6", "suit": "♥", "color": "red", "icon": GiCard6Hearts},
    {"value": 7, "number": "7", "suit": "♥", "color": "red", "icon": GiCard7Hearts},
    {"value": 8, "number": "8", "suit": "♥", "color": "red", "icon": GiCard8Hearts},
    {"value": 9, "number": "9", "suit": "♥", "color": "red", "icon": GiCard9Hearts},
    {"value": 10, "number": "10", "suit": "♥", "color": "red", "icon": GiCard10Hearts},
    {"value": 11, "number": "J", "suit": "♥", "color": "red", "icon": GiCardJackHearts},
    {"value": 12, "number": "Q", "suit": "♥", "color": "red", "icon": GiCardQueenHearts},
    {"value": 13, "number": "K", "suit": "♥", "color": "red", "icon": GiCardKingHearts},
    {"value": 1, "number": "A", "suit": "♦", "color": "red", "icon": GiCardAceDiamonds},
    {"value": 2, "number": "2", "suit": "♦", "color": "red", "icon": GiCard2Diamonds},
    {"value": 3, "number": "3", "suit": "♦", "color": "red", "icon": GiCard3Diamonds},
    {"value": 4, "number": "4", "suit": "♦", "color": "red", "icon": GiCard4Diamonds},
    {"value": 5, "number": "5", "suit": "♦", "color": "red", "icon": GiCard5Diamonds},
    {"value": 6, "number": "6", "suit": "♦", "color": "red", "icon": GiCard6Diamonds},
    {"value": 7, "number": "7", "suit": "♦", "color": "red", "icon": GiCard7Diamonds},
    {"value": 8, "number": "8", "suit": "♦", "color": "red", "icon": GiCard8Diamonds},
    {"value": 9, "number": "9", "suit": "♦", "color": "red", "icon": GiCard9Diamonds},
    {"value": 10, "number": "10", "suit": "♦", "color": "red", "icon": GiCard10Diamonds},
    {"value": 11, "number": "J", "suit": "♦", "color": "red", "icon": GiCardJackDiamonds},
    {"value": 12, "number": "Q", "suit": "♦", "color": "red", "icon": GiCardQueenDiamonds},
    {"value": 13, "number": "K", "suit": "♦", "color": "red", "icon": GiCardKingDiamonds},
    {"value": 99, "number": "JOKER", "suit": "♠", "color": "black", "icon": GiCardJoker},
    {"value": 99, "number": "JOKER", "suit": "♥", "color": "red", "icon": GiCardJoker},
]